name: serenitybyfatima
description: Serenity By Fatima

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  animated_text_kit: ^4.2.2
  flutter_native_contact_picker: ^0.0.4
  youtube_video_info: ^1.0.2
  url_launcher: ^6.1.14
  geolocator: ^10.0.1
  permission_handler: ^11.0.0
  flutter_sms:
    path: /Users/noraizeaamir/Downloads/flutter_sms-master

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - android/app/src/main/res/

  fonts:
    - family: Adelia
      fonts:
        - asset: assets/fonts/adelia.ttf
    - family: Quinger
      fonts:
        - asset: assets/fonts/Quinger.otf
        - asset: assets/fonts/Quinger.ttf
